{% set name = "sqladmin" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqladmin-{{ version }}.tar.gz
  sha256: d313da29a28763f7a7053483ccb6bbc97b56ef19f51f370e8ebc9feebd8a1056

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jinja2
    - python >=3.7
    - python-multipart
    - sqlalchemy >=1.4,<1.5
    - starlette
    - typing_extensions >=4.0
    - wtforms >=3,<4

test:
  imports:
    - sqladmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aminalaee/sqladmin
  doc_url: https://aminalaee.github.io/sqladmin
  summary: Admin interface for SQLAlchemy.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
