{% set name = "sqladmin" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqladmin-{{ version }}.tar.gz
  sha256: e8f0691250395256b4d0f9739e87bd465b8f5732d59e29d378a79bfcccda4fa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - sqlalchemy >=1.4
    - starlette
    - typing_extensions >=4.0
    - wtforms >=3,<4

    # From starlette[full]
    - itsdangerous
    - jinja2
    - python-multipart
    - pyyaml
    - httpx >=0.22.0

test:
  imports:
    - sqladmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aminalaee/sqladmin
  doc_url: https://aminalaee.github.io/sqladmin
  summary: Admin interface for SQLAlchemy.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
