{% set name = "sqladmin" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqladmin-{{ version }}.tar.gz
  sha256: d23bfce1527495550084ed50f49af3c38fd988704643429c78b62d9f93f8677a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - jinja2
    - python >=3.8
    - sqlalchemy >=1.4
    - starlette
    - wtforms >=3.1,<3.2
    - python-multipart

    # Not listed upstream but needed anyway
    - itsdangerous

test:
  imports:
    - sqladmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aminalaee/sqladmin
  doc_url: https://aminalaee.github.io/sqladmin
  summary: Admin interface for SQLAlchemy.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
