{% set name = "sqladmin" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqladmin-{{ version }}.tar.gz
  sha256: cb455b79eb79ef7d904680dd83817bf7750675147400b5b7cc401d04bda7ef2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - starlette
    - sqlalchemy >=1.4
    - wtforms >=3.1,<3.2
    - jinja2
    - python-multipart

    # Not listed upstream but needed anyway
    - itsdangerous

test:
  imports:
    - sqladmin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aminalaee/sqladmin
  doc_url: https://aminalaee.github.io/sqladmin
  summary: Admin interface for SQLAlchemy.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
