schema_version: 1

context:
  name: sqladmin
  version: 0.21.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqladmin-${{ version }}.tar.gz
  sha256: cb455b79eb79ef7d904680dd83817bf7750675147400b5b7cc401d04bda7ef2c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - starlette
    - sqlalchemy >=1.4
    - wtforms >=3.1,<3.2
    - jinja2
    - python-multipart
    # Not listed upstream but needed anyway
    - itsdangerous

tests:
  - python:
      imports:
        - sqladmin
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Admin interface for SQLAlchemy.
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://github.com/aminalaee/sqladmin
  documentation: https://aminalaee.github.io/sqladmin

extra:
  recipe-maintainers:
    - thewchan
