schema_version: 1

context:
  name: sqladmin
  version: "0.27.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqladmin-${{ version }}.tar.gz
  sha256: f3a20a1b2b991754b82bf1973131690c6eb48c94a191423fb886497355a9fcd9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - uv-build >=0.9.17,<0.12.0
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - starlette >=0.50,<2.0.0
    - wtforms >=3.1,<3.2
    - jinja2
    - python-multipart
    - sqlalchemy >=2.0
    # Not listed upstream but needed anyway
    - itsdangerous

tests:
  - python:
      imports:
        - sqladmin
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Admin interface for SQLAlchemy.
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://github.com/aminalaee/sqladmin
  documentation: https://aminalaee.github.io/sqladmin

extra:
  recipe-maintainers:
    - thewchan
